#include QMK_KEYBOARD_H
#include "keymap_extras/keymap_french_osx.h"

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum {
    R_PARATEN= SAFE_RANGE,
    R_BRACKET,
    R_BRACKET2,
    R_PARATEN_R 
};

/* const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_gergo(
			LT(2,KC_ESC), 			KC_Q, 		KC_W, 	KC_E, 	KC_R, 		KC_T, 												                KC_Y,		KC_U, 		KC_I, 		KC_O, 		KC_P, 		KC_BSPC, 
			MT(MOD_LCTL,KC_BSPC), 	LT(3,KC_A), LT(4,KC_S), 	KC_D, 	LT(2,KC_F), KC_G, KC_BTN2, 							KC_TRNS, 	KC_H,		KC_J, 		KC_K, 		KC_L, 		KC_SCLN, 	KC_ENT, 
			KC_LSFT, 				KC_Z, 		KC_X, 	KC_C, 	KC_V, 		KC_B, KC_BTN1,	KC_BTN3, 	KC_PGDN,	KC_BSPC, 	KC_N, 		KC_M, 		KC_COMM, 	KC_DOT, 	KC_SLSH, 	KC_RSFT, 	
				MT(MOD_LALT,KC_DEL), MT(MOD_LGUI,KC_SPACE),LT(1,KC_SPC), LT(2,KC_ESC), 												LT(1,KC_DEL), LT(2,KC_ENT), LT(2,KC_SPC), KC_TAB ),

	
	[1] = LAYOUT_gergo(
			KC_NUBS, 				KC_NUBS, 	KC_1, 		KC_2, 		KC_3, 		KC_4, 													KC_7, 		KC_8, 		KC_9, 		KC_0, 		KC_MINS, 	KC_EQL, 
			KC_TRNS, 				KC_HASH,	KC_DLR, 	KC_LPRN, 	KC_RPRN, 	KC_GRV,		KC_5, 							KC_6,		KC_PLUS, 	KC_MINS, 	KC_SLSH, 	KC_ASTR, 	KC_QUOT, 	KC_RBRC, 
			KC_LSFT, 				KC_PERC, 	KC_CIRC, 	KC_LBRC, 	KC_RBRC, 	KC_TILD, 	KC_TRNS, KC_TRNS, 		KC_TRNS,KC_TRNS, 	KC_AMPR, 	KC_EQL, 	KC_COMM, 	KC_DOT, 	KC_SLSH, 	KC_RSFT, 
					KC_TRNS, KC_TRNS, KC_SCLN, KC_EQL, 																			KC_EQL, KC_SCLN, KC_PGUP, KC_DEL),


	[2] = LAYOUT_gergo(
			KC_TRNS, 				KC_1, 		KC_2, 		KC_3, 		KC_4, 		KC_5, 													R_BRACKET, 	R_PARATEN, 	KC_UP, 		KC_9, 		KC_0, 		KC_TRNS, 
			KC_TRNS, 				KC_F1, 		KC_F2, 		KC_F3, 		KC_F4, 		KC_F5, 		KC_F6, 							KC_TRNS, 	R_BRACKET2, KC_LEFT, 	KC_DOWN, 	KC_RGHT, 	KC_VOLD, 	KC_VOLU, 
			KC_TRNS, 				KC_F7, 		KC_F8, 		KC_F9, 		KC_F10,		KC_F11, 	KC_F12, KC_TRNS, 		KC_TRNS, KC_TRNS, 	KC_MS_L, 	KC_MS_D, 	KC_MS_U, 	KC_MS_R, 	KC_MPLY, 	KC_MNXT, 
					KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 																		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),


	[3] = LAYOUT_gergo(
			KC_NO, 					KC_NO, 		KC_NO, 		KC_NO, 		KC_NO, 		KC_NO, 															KC_RCBR, 	KC_AMPR, 	KC_ASTR, 	KC_LPRN, 	KC_MINS, 	KC_BSPC, 	
			KC_NO, 					KC_NO,		KC_NO, 		KC_NO, 		KC_NO, 		KC_NO, 		KC_NO, 									KC_NO, 		KC_QUES, 	KC_DLR, 	KC_PERC, 	KC_CIRC, 	KC_PLUS, 	KC_PLUS, 	
			KC_NO, 					KC_NO, 		KC_NO, 		KC_NO,      KC_NO, 		KC_NO, 		KC_NO, 		KC_NO, 		KC_NO, 			KC_NO, 		KC_NO, 		KC_EXLM, 	KC_AT, 		KC_HASH, 	KC_ENT, 	KC_NO, 		
						KC_NO, 		KC_NO, 		KC_NO, 		KC_NO, 										  s											KC_NO, 		KC_NO, 		KC_RPRN, 	KC_GT),
  
  [4] = LAYOUT_gergo(
			KC_NO, 					KC_NO, 		KC_NO, 		KC_NO, 		KC_NO, 		KC_NO, 															KC_RCBR, 	KC_AMPR, 	KC_ASTR, 	KC_LPRN, 	KC_MINS, 	KC_BSPC, 	
			KC_NO, 					KC_NO,		KC_NO, 		KC_NO, 		KC_NO, 		KC_NO, 		KC_NO, 									KC_NO, 		KC_QUES, 	KC_DLR, 	KC_PERC, 	KC_CIRC, 	KC_PLUS, 	KC_PLUS, 	
			KC_NO, 					KC_NO, 		KC_NO, 		KC_NO,      KC_NO, 		KC_NO, 		KC_NO, 		KC_NO, 		KC_NO, 			KC_NO, 		KC_NO, 		KC_EXLM, 	KC_AT, 		KC_HASH, 	KC_ENT, 	KC_NO, 		
						KC_NO, 		KC_NO, 		KC_NO, 		KC_NO, 																					KC_NO, 		KC_NO, 		KC_RPRN, 	KC_GT)
}; */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_gergo(
			LT(2,KC_ESC), 			KC_Q, 		KC_W, 	KC_E, 	KC_R, 		KC_T, 												                KC_Y,		KC_U, 		KC_I, 		KC_O, 		KC_P, 		KC_BSPC, 
			 KC_LSFT, 				LT(3,KC_A), KC_S, 	LT(4,KC_D), LT(5,KC_F), KC_G, KC_BTN2, 							KC_TRNS, 	KC_H,		KC_J, 		KC_K, 		KC_L, 		KC_SCLN, 	KC_ENT, 
			MT(MOD_LCTL,KC_BSPC),				KC_Z, 		KC_X, 	KC_C, 	KC_V, 		KC_B, KC_BTN1,	KC_BTN3, 	KC_PGDN,	KC_BSPC, 	KC_N, 		KC_M, 		KC_COMM, 	KC_DOT, 	KC_SLSH, 	KC_RSFT, 	
				MT(MOD_LALT,KC_DEL), MT(MOD_LGUI,KC_SPACE),LT(1,KC_TAB), LT(2,KC_ESC), 												LT(1,KC_DEL), MT(MOD_LSFT,KC_ENT), LT(2,KC_SPC), KC_TAB ),

	
	[1] = LAYOUT_gergo(
			KC_NUBS, 				KC_NUBS, 	KC_1, 		KC_2, 		KC_3, 		KC_4, 													      KC_7, 		KC_8, 		KC_9, 		KC_0, 		KC_MINS, 	KC_EQL, 
			KC_TRNS, 				KC_F1,	   KC_F2, 	  KC_F3, 	  KC_F4, 	  KC_F5,		KC_F6, 							KC_6,		KC_PLUS, 	KC_MINS, 	KC_SLSH, 	KC_ASTR, 	KC_QUOT, 	KC_RBRC, 
			KC_LSFT, 				KC_F7, 	   KC_F8, 	  KC_F9, 	  KC_F10, 	  KC_F11, 	    KC_F12, KC_TRNS, 	KC_TRNS,KC_TRNS, 	KC_AMPR, 	KC_EQL, 	KC_COMM, 	KC_DOT, 	KC_SLSH, 	KC_RSFT, 
					KC_TRNS, KC_TRNS, KC_SCLN, KC_EQL, 																			KC_EQL, KC_SCLN, KC_PGUP, KC_DEL),


	[2] = LAYOUT_gergo(
			KC_TRNS, 				KC_1, 		KC_2, 		KC_3, 		KC_4, 		KC_5, 													R_BRACKET, 	R_PARATEN, 	KC_UP, 		KC_9, 		KC_0, 		KC_TRNS, 
			KC_TRNS, 				KC_F1, 		KC_F2, 		KC_F3, 		KC_F4, 		KC_F5, 		KC_F6, 							KC_TRNS, 	R_BRACKET2, KC_LEFT, 	KC_DOWN, 	KC_RGHT, 	KC_VOLD, 	KC_VOLU, 
			KC_TRNS, 				KC_F7, 		KC_F8, 		KC_F9, 		KC_F10,		KC_F11, 	KC_F12, KC_TRNS, 		KC_TRNS, KC_TRNS, 	KC_MS_L, 	KC_PGDN, 	KC_PGUP, 	KC_MS_R, 	KC_MPLY, 	KC_MNXT, 
					KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 																		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),


	[3] = LAYOUT_gergo(
			KC_TRNS, 					KC_TRNS, 		KC_TRNS, 		KC_TRNS, 		KC_TRNS, 		KC_TRNS, 															KC_RCBR, 	KC_AMPR, 	KC_ASTR, 	KC_LPRN, 	KC_MINS, 	KC_BSPC, 	
			KC_TRNS, 					KC_TRNS,		KC_TRNS, 		KC_TRNS, 		KC_TRNS, 		KC_TRNS, 		KC_TRNS, 									KC_TRNS, 		KC_QUES, 	KC_DLR, 	KC_PERC, 	KC_CIRC, 	KC_PLUS, 	KC_PLUS, 	
			KC_TRNS, 					KC_TRNS, 		KC_TRNS, 		KC_TRNS,      KC_TRNS, 		KC_TRNS, 		KC_TRNS, 		KC_TRNS, 		KC_TRNS, 			KC_TRNS, 		KC_TRNS, 		KC_EXLM, 	KC_AT, 		KC_HASH, 	KC_ENT, 	KC_NO, 		
						KC_TRNS, 		KC_TRNS, 		KC_TRNS, 		KC_TRNS, 																					KC_TRNS, 		KC_TRNS, 		KC_RPRN, 	KC_GT),
  
  [4] = LAYOUT_gergo(
			KC_TRNS, 					KC_TRNS, 		KC_TRNS, 		FR_PLUS, 		FR_HASH, 	FR_BSLS, 														FR_HASH, 	FR_QUOT, 	FR_EQL, 	FR_DOT, 	FR_MINS, 	KC_BSPC, 	
			KC_TRNS, 					KC_TRNS,		KC_TRNS, 		FR_EQL, 		FR_SLSH, 	FR_ASTR, 	KC_TRNS, 							  KC_TRNS,      FR_LABK, 	FR_LPRN, 	FR_LCBR, 	FR_LBRC, 	FR_QUES, 	KC_ENT, 	
			KC_TRNS, 					KC_TRNS, 		KC_TRNS, 		FR_MINS,    FR_COLN, 	FR_PIPE, 	KC_TRNS, 		KC_TRNS, 		KC_TRNS,  KC_TRNS, 		FR_DLR, 	FR_SLSH, 	FR_COMM, 	FR_PIPE, 	FR_ASTR, 	KC_RSFT, 	 		
						KC_TRNS, 		KC_TRNS, 		KC_TRNS, 		KC_TRNS, 																					KC_TRNS, 		KC_TRNS, 		KC_RPRN, 	KC_GT),


  [5] = LAYOUT_gergo(
			KC_TRNS, 					KC_TRNS, 		KC_TRNS, 		FR_PLUS, 		FR_HASH, 	FR_BSLS, 														FR_AT, 		FR_DQUO, 	FR_PLUS, 	FR_COLN, 	FR_UNDS, 	KC_BSPC, 	
			KC_TRNS, 					KC_TRNS,		KC_TRNS, 		FR_EQL, 		FR_SLSH, 	FR_ASTR, 	KC_TRNS, 								KC_TRNS, 	FR_RABK, 	FR_RPRN, 	FR_RCBR, 	FR_RBRC, 	FR_QUES, 	KC_ENT, 	
			KC_TRNS, 					KC_TRNS, 		KC_TRNS, 		FR_MINS,    FR_COLN, 	FR_PIPE, 	KC_TRNS, 		KC_TRNS, 		   KC_TRNS,   KC_TRNS, 	FR_DLR, 	FR_BSLS, 	FR_SCLN, 	FR_AMPR, 	FR_ASTR, 	KC_RSFT, 	 		
						KC_TRNS, 		KC_TRNS, 		KC_TRNS, 		  KC_TRNS, 																					KC_TRNS, 		KC_TRNS, 		KC_RPRN, 	KC_GT)/* ,
[6] = LAYOUT_gergo(
			KC_TRNS, 					KC_TRNS, 		KC_TRNS, 		FR_PLUS, 		FR_HASH, 	FR_BSLS, 															    FR_DLR, 	FR_LCBR, 	FR_RCBR, 	FR_MINS, 	FR_UNDS, 	FR_AMPR, 	
			KC_TRNS, 					KC_TRNS,		KC_TRNS, 		FR_EQL, 		FR_SLSH, 	FR_ASTR, 	KC_TRNS, 									      	FR_LABK,    FR_LBRC, 	FR_LPRN, 	FR_RPRN, 	FR_RBRC, 	FR_RABK, 	FR_DOT, 	
			 KC_TRNS, 					KC_TRNS, 		KC_TRNS, 		FR_MINS,    	FR_COLN, 	FR_PIPE, 	 KC_TRNS, 		KC_TRNS, 		    				KC_TRNS,  FR_BSLS, 	FR_HASH, 	FR_SLSH, 	FR_SCLN, 	FR_COMM, 	FR_ASTR, 	FR_QUES, 	 		
						KC_TRNS, 		KC_TRNS, 		KC_TRNS, 		KC_TRNS, 																					KC_TRNS, 		KC_TRNS, 		KC_RPRN, 	KC_GT) */
};


 
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    case R_PARATEN:
      if (record->event.pressed) {
        // when keycode QMKBEST is pressed
        SEND_STRING(SS_TAP(X_5)SS_TAP(X_MINS)SS_TAP(X_LEFT));
      } else {
        // when keycode QMKBEST is released
      }
      break;

    case R_BRACKET:
      if (record->event.pressed) {
        // when keycode QMKBEST is pressed
        SEND_STRING(SS_LALT(SS_TAP(X_5))SS_LALT(SS_TAP(X_MINS))SS_TAP(X_LEFT)SS_TAP(X_ENTER));
      } else {
        // when keycode QMKBEST is released
      }
      break;
    case R_BRACKET2:
      if (record->event.pressed) {
        // when keycode QMKBEST is pressed
        SEND_STRING(SS_LSFT(SS_LALT(SS_TAP(X_5)))SS_LSFT(SS_LALT(SS_TAP(X_MINS)))SS_TAP(X_LEFT));
      } else {
        // whenkeycode QMKBEST is released
      }
      break;
    //right parathensis
    case R_PARATEN_R:
      if (record->event.pressed) {
        SEND_STRING(SS_TAP(X_5));
      } else {
        
      }
    break;

  }
  return true;
};